# Decision Trees

#### Instructions:
- Write modular code with relevant docstrings and comments for you to be able to use
functions you have implemented in future assignments.
- All theory questions and observations must be written in a markdown cell of your jupyter notebook.You can also add necessary images in `imgs/` and then include it in markdown. Any other submission method for theoretical question won't be entertained.
- Start the assignment early, push your code regularly and enjoy learning!

<b>Name: </b> Anjali Singh <br>
<b>Roll No.: </b>2020102004 <br>

### Question 1 Optimal DT from table
**[20 points]**\
We will use the dataset below to learn a decision tree which predicts if people pass machine
learning (Yes or No), based on their previous GPA (High, Medium, or Low) and whether or
not they studied. 

| GPA | Studied | Passed |
|:---:|:-------:|:------:|
|  L  |    F    |    F   |
|  L  |    T    |    T   |
|  M  |    F    |    F   |
|  M  |    T    |    T   |
|  H  |    F    |    T   |
|  H  |    T    |    T   |
    
 For this problem, you can write your answers using $log_2$
, but it may be helpful to note
that $log_2 3 ≈ 1.6$.

---
1. What is the entropy H(Passed)?
2. What is the entropy H(Passed | GPA)?
3. What is the entropy H(Passed | Studied)?
4. Draw the full decision tree that would be learned for this dataset. You do
not need to show any calculations.
---


<b> 1. What is the entropy H(passed)? </b><br>

$ H(passed) = -p_{true}log_2p_{true} - p_{false}log_2p_{false}  \newline
p_{true} = 4/6 = 2/3; \newline
p_{false} = 2/6 = 1/3; \newline
\implies H(passed) = -((2/3)log_2(2/3) + (1/3)log_2(1/3)) \newline
$
<br>
After calculations, we get <br>
$ H(passed) = 0.934 $

<b> 2. What is the entropy H(passed|GPA)? </b><br>
$$ H(X|Y) = \sum_{x\epsilon X}\sum_{y\epsilon Y} P(x, y)log_2 (P(y)/P(x, y))

\newline
 \implies H(passed | GPA) = \sum \sum P(passed, GPA)log_2 P(GPA)/P(passed, GPA) 
 \newline
 \implies P(passed, GPA) = 2/6 * 1/2 \space for \space GPA = L, M \newline
 \implies P(passed, GPA) = 2/6 * 1 \space for \space GPA = H \newline
 \implies H(passed | GPA) = ((2/6*1/2)log_2(1/6)/(1/6)) * 4 + ((2/6 * 1)log_2(2/6)/(2/6)) \newline
 \implies H(passed | GPA) = 0.667
$$

<b> 3. What is entropy H(passed | Studied)? </b><br>
$$ H(X|Y) = \sum_{x\epsilon X}\sum_{y\epsilon Y} P(x, y)log_2 (P(y)/P(x, y))
\newline
\implies H(passed | studied) = ((1/2 * 1/2)log_2(1/2)/(1/4)) * 4 + ((1/2 * 1)log_2(1/2)/(1/2)) * 2 \newline
\implies H(passed | studied) = 1
$$


<b> 4. Draw the full decision tree that would be learned for this dataset. </b><br>


### Question 2 DT loss functions
**[10 points]**
1. Explain Gini impurity and Entropy. 
2. What are the min and max values for both Gini impurity and Entropy
3. Plot the Gini impurity and Entropy for $p\in[0,1]$.
4. Multiply Gini impurity by a factor of 2 and overlay it over entropy.

<b>1. Explain Gini impurity and Entropy. </b><br>
<b>Entropy: </b> It is one of the ways to measure the impurity in the collection of data, i.e., non-homogeneity. It returns the information about the dataset that how impure the data is. 
Given a collection of dataset $S$, and the probability for classes is represented by $p_i$, entropy can be calculated as: - <br>
$ Entropy = -\sum p_ilog_2(p_i) $ 
<br><br>
<b> Gini Impurity: </b> It is a measurement used to build decision trees to determine how the features of a dataset should split nodes to form the tree. It usually $ \epsilon\space [0, 0.5] $. <br>
As taught in the class, it can also be referred to as an extended variance impurity to three classes: $ p(w_1) p(w_2) p(w_3) $ <br>
$ i(N) = p(w_1)p(w_2) + p(w_2)p(w_3) + p(w_3)p(w_1) $ <br>
For a dataset $D$ that contains samples from $k$ classes. The probability of samples belonging to class $i$ at a given node can be denoted as $p_i$. Then, <br>
$ gini(D) = 1 - \sum_{i=1}^{k}p_i^2 $

<b>2. What are the min and max values for both Gini impurity and Entropy? </b><br>
Min value of gini impurity: 0 <br>
max value of gini impurity: 0.5 <br>
min value of entropy: 0 <br>
max value of entropy: 1 <br>

<b>3. Plot the Gini impurity and Entropy for $p\in[0,1]$ </b><br>

<b>4. Multiply Gini impurity by a factor of 2 and overlay it over entropy. </b><br>
$ gini \epsilon [0, 0.5] $ <br>
$ entropy \epsilon [0, 1] $ <br>

$ gini*2 \space\epsilon\space [0, 1] $

### Question 3 Training a Decision Tree  
**[40 points]**

You can download the spam dataset from the link given below. This dataset contains feature vectors and the lables of Spam/Non-Spam mails. 
http://archive.ics.uci.edu/ml/machine-learning-databases/spambase/spambase.data

**NOTE: The last column in each row represents whether the mail is spam or non spam**\
Although not needed, incase you want to know what the individual columns in the feature vector means, you can read it in the documentation given below.
http://archive.ics.uci.edu/ml/machine-learning-databases/spambase/spambase.DOCUMENTATION

**Download the data and load it from the code given below**

In [4]:
import numpy as np
import csv
import pandas as pd
from sklearn import preprocessing

In [5]:

#######################
# Your code goes here #

raw_data = pd.read_csv("spambase.data", header=None)
data = raw_data.values
print(data.shape)
print(data)
#######################

(4601, 58)
[[0.000e+00 6.400e-01 6.400e-01 ... 6.100e+01 2.780e+02 1.000e+00]
 [2.100e-01 2.800e-01 5.000e-01 ... 1.010e+02 1.028e+03 1.000e+00]
 [6.000e-02 0.000e+00 7.100e-01 ... 4.850e+02 2.259e+03 1.000e+00]
 ...
 [3.000e-01 0.000e+00 3.000e-01 ... 6.000e+00 1.180e+02 0.000e+00]
 [9.600e-01 0.000e+00 0.000e+00 ... 5.000e+00 7.800e+01 0.000e+00]
 [0.000e+00 0.000e+00 6.500e-01 ... 5.000e+00 4.000e+01 0.000e+00]]


You can try to normalize each column (feature) separately with either one of the following ideas. **Do not normalize labels**.
- Shift-and-scale normalization: substract the minimum, then divide by new maximum. Now all values are between 0-1
- Zero mean, unit variance : substract the mean, divide by the appropriate value to get variance=1.

Normalization formula used here: <br>
[Shift-and-scale normalization] <br>
$$ x_{norm} = (x-x_{min})/(x_{max}-x_{min}) $$

In [7]:
# ML algos tend to perform better or converge faster when the different features (variables)
# are on a smaller scale. 

def normalize(data):
    # normalize a 2D matrix dataset 
    # return a normalized 2D matrix dataset
    # YOUR CODE HERE
    row, col = data.shape
    for i in range(col-1):
        data[:,i] = (data[:,i] - data[:,i].min())/(data[:,i].max() - data[:,i].min())
        
    return data

In [10]:
data_norm = normalize(data)
print('Normalized Data Shape: ', data_norm.shape)
print(data_norm)

Normalized Data Shape:  (4601, 58)
[[0.00000000e+00 4.48179272e-02 1.25490196e-01 ... 6.00720865e-03
  1.74873737e-02 1.00000000e+00]
 [4.62555066e-02 1.96078431e-02 9.80392157e-02 ... 1.00120144e-02
  6.48358586e-02 1.00000000e+00]
 [1.32158590e-02 0.00000000e+00 1.39215686e-01 ... 4.84581498e-02
  1.42550505e-01 1.00000000e+00]
 ...
 [6.60792952e-02 0.00000000e+00 5.88235294e-02 ... 5.00600721e-04
  7.38636364e-03 0.00000000e+00]
 [2.11453744e-01 0.00000000e+00 0.00000000e+00 ... 4.00480577e-04
  4.86111111e-03 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.27450980e-01 ... 4.00480577e-04
  2.46212121e-03 0.00000000e+00]]


1. Split your data into train 80% and test dataset 20% 
2. **[BONUS]** Visualize the data using PCA . You can reduce the dimension of the data if you want. Bonus marks if this increases your accuracy.

*NOTE: If you are applying PCA or any other type of dimensionality reduction, do it before splitting the dataset*

In [11]:

#######################
# Your code goes here #

def pca(data, num_components):
    # finding eigen values and eigen vectors using pca method for the dataset
    # returning the first num_components of eigen vectors

    row, col = data.shape
    mean = np.mean(data, axis=0)
    data = data - mean
    cov = np.cov(data, rowvar=False)

    eigen_values, eigen_vectors = np.linalg.eig(cov)
    eigen_vectors = eigen_vectors[:, np.argsort(eigen_values)[::-1]]
    eigen_vectors = eigen_vectors[:, :num_components]
    
    data_reduced = np.dot(data, eigen_vectors)

    return data_reduced


In [12]:
# implementing the above pca function to reduce the dimension of the given dataset

data_pca = pca(data_norm, 2)

print(data_pca)

[[ 0.60371339  0.00161239]
 [ 0.62378346 -0.01153851]
 [ 0.63452676  0.01365266]
 ...
 [-0.39005723 -0.07295247]
 [-0.39012632 -0.07298202]
 [-0.37882707 -0.08828848]]


In [14]:
# split the dataset into 80% training and 20% testing

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data_pca, data[:,57], test_size=0.2, random_state=42)

print('X_train:\n', X_train, '\ny_train:\n', y_train)

X_train:
 [[ 0.61878897  0.00203542]
 [-0.39833867 -0.05839492]
 [-0.37017848 -0.05752039]
 ...
 [-0.41310154  0.07558908]
 [-0.40681537 -0.00923127]
 [ 0.59307753  0.0165655 ]] 
y_train:
 [1. 0. 0. ... 0. 0. 1.]


You need to perform a K fold validation on this and report the average training error over all the k validations. 
- For this , you need to split the training data into k splits.
- For each split, train a decision tree model and report the training , validation and test scores.
- Report the scores in a tabular form for each validation

In [15]:
from sklearn.model_selection import KFold
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [16]:
# split the data into k splits 
def k_fold_split(data, k):
    # splitting the dataset into k folds
    # returning a list of k folds
    
    data_split = []
    data_copy = list(data)
    fold_size = int(len(data) / k)
    for i in range(k):
        fold = []
        while len(fold) < fold_size:
            index = np.random.randint(len(data_copy))
            fold.append(data_copy.pop(index))
        data_split.append(fold)
    return data_split

# find data-split

data_split = k_fold_split(data_pca, 7)
# print('Data Split:\n', data_split)

In [17]:
from sklearn.tree import DecisionTreeClassifier

In [18]:
# for each split, train a decision tree model using DecisionTreeClassifier
# use the above k_fold_split function to split the dataset into k splits
# use the first k-1 splits to train the model and the last split to test the model

def decision_tree_model(data, k):
    # train a decision tree model using DecisionTreeClassifier
    # return the accuracy of the model
    data_split = k_fold_split(data, k)
    scores = []
    for i in range(len(data_split)):
        train_set = list(data_split)
        train_set.pop(i)
        train_set = sum(train_set, [])
        test_set = []
        for row in data_split[i]:
            row_copy = list(row)
            test_set.append(row_copy)
            row_copy[-1] = None
        y_train = [row[-1] for row in train_set]
        X_train = [row[:-1] for row in train_set]
        y_test = [row[-1] for row in test_set]
        X_test = [row[:-1] for row in test_set]
        model = DecisionTreeClassifier()
        model.fit(X_train, y_train)
        predictions = model.predict(X_test)
        accuracy = accuracy_score(y_test, predictions)
        scores.append(accuracy)
    return scores
    

In [19]:
# finding training, validation and testing scores
scores = decision_tree_model(data_pca, 5)
print('Scores:\n', scores)
print('Mean Accuracy: %.3f%%' % (sum(scores)/float(len(scores))))

ValueError: Unknown label type: 'continuous'

In [18]:
# test_split function row wise for a 2D matrix 
def test_split(index, value, data):
    # split the dataset into two based on the index and value
    # return two datasets
    left, right = [], []
    for row in data:
        if row[index] < value:
            left.append(row)
        else:
            right.append(row)
    return left, right

In [19]:
# gini index function
def gini_index(groups, classes):
    # calculate the gini index for a split dataset
    # return the gini index
    n_instances = float(sum([len(group) for group in groups]))
    gini = 0.0
    for group in groups:
        size = float(len(group))
        if size == 0:
            continue
        score = 0.0
        for class_val in classes:
            p = [row[-1] for row in group].count(class_val) / size
            score += p * p
        gini += (1.0 - score) * (size / n_instances)
    return gini

In [20]:
# for each split, train a decision tree model using DescisionTreeClassifier from sklearn
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn import tree

In [21]:
def decision_tree(X_train, y_train, X_test, y_test):
    # train a decision tree model using DescisionTreeClassifier from sklearn
    # return the accuracy of the model
    dt = DecisionTreeClassifier()
    dt.fit(X_train, y_train)
    y_pred = dt.predict(X_test)

    # print('Predicted Values:\n', y_pred)

    tree.plot_tree(dt)

    accuracy = accuracy_score(y_test, y_pred)

    return accuracy

In [22]:
# Initialize K and split the data
k = 3
kf = KFold(n_splits = k, shuffle = True, random_state = 42)
n_neighbors = 7

#Run the K fold Validation and report the scores
# For each split, train a decision tree model and report the training, validation and test scores
scores = []

for train_index, test_index in kf.split(X_train):
    X_train_train, X_test_val = X_train[train_index], X_train[test_index]
    y_train_train, y_test_val = y_train[train_index], y_train[test_index]
    knn = KNeighborsClassifier(n_neighbors = 7)
    knn.fit(X_train_train, y_train_train)
    y_pred = knn.predict(X_test_val)
    y_train_pred = knn.predict(X_train_train)

    scores.append(accuracy_score(y_test_val, y_pred))

    print('Training Accuracy: ', accuracy_score(y_train_train, y_train_pred))
    print('Validation Accuracy: ', accuracy_score(y_test_val, y_pred))

# Train the model on the training set and report the test score
# YOUR CODE HERE
knn = KNeighborsClassifier(n_neighbors = 7)
knn.fit(X_train, y_train)
y_test_pred = knn.predict(X_test)
print('Test Accuracy: ', accuracy_score(y_test, y_test_pred))

print('KNN Accuracy: ', np.mean(scores))




Training Accuracy:  1.0
Validation Accuracy:  1.0
Training Accuracy:  1.0
Validation Accuracy:  1.0
Training Accuracy:  1.0
Validation Accuracy:  1.0
Test Accuracy:  1.0
KNN Accuracy:  1.0


### Question 4 Random Forest Algorithm
**[30 points]**

1. What is boosting, bagging and  stacking?
Which class does random forests belong to and why? **[5 points]**

<br><br>
<b>Boosting: </b> It is an ensemble learning method that combines a set of weak learners into a strong learner to minimize training errors. <br>
A random sample of data is selected, fitted with a model and then trained sequentially. 
<br><br>
<b>Bagging: </b> It is the ensemble learning method that is commonly used to reduce variance within a noisy dataset. <br>
A random sample of data in a training set is selected with replacement, i.e., the individual data points can be chosen more than once. These weak models are trained independently, and depending on it - regression or classification can be performed. <br>
It helps in improving the performance and accuracy of algorithms. It is also known as Bootstrap Aggregation. 
<br><br>
<b>Stacking: </b> It is the ensemble learning method which is used to predict multiple nodes to build a new model and improve model performance. <br>
It basically helps us to train multiple models to solve similar problems, and based on their combined output, it builds a new model with improved performance. <br>
It uses different ML models one after the other, wherein we add the predictions from each model to make a new feature. 
<br><br>
Random forest algorithm is an extension of bagging method, and therefore, it is an ensemble learning method for classification, regression and other tasks. This comes under the class of bagging as it utilizes both bagging and feature randomness to create an uncorrelated forest of decision trees. 

2. Implement random forest algorithm using different decision trees. **[25 points]** 

In [1]:
# Pass necessary params as per requirements
    #######################
    # Your code goes here #
# implement random forest algorithm using different decision trees from scratch
# implement the function using the above decision tree function
# return the accuracy of the model
def random_forest_algorithm(data, max_depth, min_size, sample_size, n_trees):
    # find the training, validation and test scores
    data_split = k_fold_split(data, 5)
    train_scores, val_scores, test_scores = list(), list(), list()
    for i in range(len(data_split)):
        train_set, test_set = test_split(i, data_split)
        train_set, val_set = test_split(i, train_set)
        tree = decision_tree(X_train, y_train, X_test, y_test)
        train_score = accuracy_score(train_set, tree)
        val_score = accuracy_score(val_set, tree)
        test_score = accuracy_score(test_set, tree)
        train_scores.append(train_score)
        val_scores.append(val_score)
        test_scores.append(test_score)
    return train_scores, val_scores, test_scores

# implement random forest algorithm on the given dataset
# return the accuracy of the model
accuracy = random_forest_algorithm(data_norm, 2, 1, 1.0, 5)
print('Accuracy: ', accuracy)
    #######################

NameError: name 'data_norm' is not defined